# Generated by Django 4.1.3 on 2023-03-19 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Club name cannot contain numbers and special characters in their name.', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='theme',
            field=models.CharField(choices=[('NO', 'None'), ('E', 'Ebooks'), ('A', 'Arts'), ('BM', 'Biographies & Memoirs'), ('BI', 'Business & Investing'), ('C', 'Comics'), ('CT', 'Computers & Technology'), ('CF', 'Cookery, Food & Wine'), ('F', 'Fantasy'), ('FL', 'Fiction & Literature'), ('G', 'Gardening'), ('HF', 'Health & Fitness'), ('HM', 'Health, Mind & Body'), ('H', 'History'), ('M', 'Mystery & Thrillers'), ('N', 'Nature'), ('P', 'Poetry'), ('PC', 'Politics & Current Affairs'), ('R', 'Reference'), ('RO', 'Romance'), ('RS', 'Religion & Spirituality'), ('S', 'Science'), ('SF', 'Science Fiction'), ('SP', 'Sports'), ('T', 'Travel'), ('Y', 'Young Adult')], default=('NO', 'None'), max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='in_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_posts', to='blogs.club'),
        ),
    ]
