# Generated by Django 4.1.3 on 2023-03-23 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Club name cannot contain numbers and special characters in their name.', regex='^[a-zA-Z0-9_ ]*$')]),
        ),
    ]
