# Generated by Django 4.1.3 on 2023-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_genre',
            field=models.CharField(blank=True, choices=[('E', 'Ebooks'), ('A', 'Arts'), ('BM', 'Biographies & Memoirs'), ('BI', 'Business & Investing'), ('C', 'Comics'), ('CT', 'Computers & Technology'), ('CF', 'Cookery, Food & Wine'), ('F', 'Fantasy'), ('FL', 'Fiction & Literature'), ('G', 'Gardening'), ('HF', 'Health & Fitness'), ('HM', 'Health, Mind & Body'), ('H', 'History'), ('M', 'Mystery & Thrillers'), ('N', 'Nature'), ('P', 'Poetry'), ('PC', 'Politics & Current Affairs'), ('R', 'Reference'), ('RO', 'Romance'), ('RS', 'Religion & Spirituality'), ('S', 'Science'), ('SF', 'Science Fiction'), ('SP', 'Sports'), ('T', 'Travel'), ('Y', 'Young Adult')], default='', max_length=2),
        ),
    ]
