# Generated by Django 4.1.3 on 2023-03-23 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_featuredbook_curator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favourite_genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO", "None"),
                    ("E", "Ebooks"),
                    ("A", "Arts"),
                    ("BM", "Biographies & Memoirs"),
                    ("BI", "Business & Investing"),
                    ("C", "Comics"),
                    ("CT", "Computers & Technology"),
                    ("CF", "Cookery, Food & Wine"),
                    ("F", "Fantasy"),
                    ("FL", "Fiction & Literature"),
                    ("G", "Gardening"),
                    ("HF", "Health & Fitness"),
                    ("HM", "Health, Mind & Body"),
                    ("H", "History"),
                    ("M", "Mystery & Thrillers"),
                    ("N", "Nature"),
                    ("P", "Poetry"),
                    ("PC", "Politics & Current Affairs"),
                    ("R", "Reference"),
                    ("RO", "Romance"),
                    ("RS", "Religion & Spirituality"),
                    ("S", "Science"),
                    ("SF", "Science Fiction"),
                    ("SP", "Sports"),
                    ("T", "Travel"),
                    ("Y", "Young Adult"),
                ],
                default=("NO", "None"),
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blogs.post",
                    ),
                ),
            ],
        ),
    ]
