# Generated by Django 4.1.3 on 2023-03-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_user_favourite_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=255, verbose_name="ISBN")),
                (
                    "book_title",
                    models.CharField(max_length=255, verbose_name="Book-Title"),
                ),
                (
                    "book_author",
                    models.CharField(max_length=255, verbose_name="Book-Author"),
                ),
                (
                    "year_of_publication",
                    models.IntegerField(verbose_name="Year-Of-Publication"),
                ),
                (
                    "publisher",
                    models.CharField(max_length=255, verbose_name="Publisher"),
                ),
                (
                    "image_url_s",
                    models.CharField(max_length=255, verbose_name="Image-URL-S"),
                ),
                (
                    "image_url_m",
                    models.CharField(max_length=255, verbose_name="Image-URL-M"),
                ),
                (
                    "image_url_l",
                    models.CharField(max_length=255, verbose_name="Image-URL-L"),
                ),
            ],
        ),
    ]
