# Generated by Django 4.1.3 on 2023-03-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_club_name_alter_club_owner_alter_club_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year_of_publication',
            field=models.CharField(max_length=5, verbose_name='Year-Of-Publication'),
        ),
    ]
