# Generated by Django 4.1.3 on 2023-03-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_books_year_of_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('eventLink', models.CharField(max_length=200)),
                ('attendees', models.ManyToManyField(related_name='upcoming_events', through='blogs.AttendEvent', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_events', to='blogs.club')),
                ('selectedBook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_events', to='blogs.books')),
            ],
        ),
        migrations.AddField(
            model_name='attendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_event', to='blogs.event'),
        ),
        migrations.AddField(
            model_name='attendevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendevent',
            unique_together={('event', 'user')},
        ),
    ]
