# Generated by Django 4.1.3 on 2023-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_alter_user_favourite_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favourite_genre",
            field=models.CharField(
                choices=[
                    ("NO", "None"),
                    ("E", "Ebooks"),
                    ("A", "Arts"),
                    ("BM", "Biographies & Memoirs"),
                    ("BI", "Business & Investing"),
                    ("C", "Comics"),
                    ("CT", "Computers & Technology"),
                    ("CF", "Cookery, Food & Wine"),
                    ("F", "Fantasy"),
                    ("FL", "Fiction & Literature"),
                    ("G", "Gardening"),
                    ("HF", "Health & Fitness"),
                    ("HM", "Health, Mind & Body"),
                    ("H", "History"),
                    ("M", "Mystery & Thrillers"),
                    ("N", "Nature"),
                    ("P", "Poetry"),
                    ("PC", "Politics & Current Affairs"),
                    ("R", "Reference"),
                    ("RO", "Romance"),
                    ("RS", "Religion & Spirituality"),
                    ("S", "Science"),
                    ("SF", "Science Fiction"),
                    ("SP", "Sports"),
                    ("T", "Travel"),
                    ("Y", "Young Adult"),
                ],
                default="NO",
                max_length=2,
            ),
        ),
    ]
