# Generated by Django 4.1.3 on 2023-03-22 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_event_address_event_location_alter_event_eventlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
                ('book_title', models.CharField(max_length=255, verbose_name='Book-Title')),
                ('book_author', models.CharField(max_length=255, verbose_name='Book-Author')),
                ('year_of_publication', models.CharField(max_length=4, verbose_name='Year-Of-Publication')),
                ('publisher', models.CharField(max_length=255, verbose_name='Publisher')),
                ('image_url_s', models.CharField(max_length=255, verbose_name='Image-URL-S')),
                ('image_url_m', models.CharField(max_length=255, verbose_name='Image-URL-M')),
                ('image_url_l', models.CharField(max_length=255, verbose_name='Image-URL-L')),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Club name cannot contain numbers and special characters in their name.', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='club',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.book'),
        ),
        migrations.AlterField(
            model_name='event',
            name='selectedBook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_events', to='blogs.book'),
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
