# Generated by Django 4.1.3 on 2023-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_book_alter_club_name_alter_club_theme_club_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
            ],
        ),
    ]
